Nama : Billy AB

Kelas : TI21F

NIM : 20210040100

#**Import Library**

---


In [ ]:
# impor library
import numpy as np
import pandas as pd

In [ ]:
data = {
    'Province': ['Banten', 'DKI Jakarta','Jawa Barat','Banten','Jawa Barat','DKI Jakarta','Banten','Banten','Jawa Barat','DKI Jakarta','Banten','Banten','Jawa Barat','DKI Jakarta','DKI Jakarta'],
    'Age': [24,np.nan,60,34,58,np.nan,21,44,40,51,32,30,30,19,25],
    'Wage': [5000000,3400000,7350000,3500000,np.nan,8000000,5500000,10000000,9000000,10500000,np.nan,6400000,np.nan,2200000,4500000],
    'Life insured': ['Yes','No','No','No','Yes','No','No','Yes','Yes','Yes','No','No','No','Yes','Yes'],
}

dataset = pd.DataFrame(data)

#**Import Dataset dari File CSV**

---


In [ ]:
# impor dataset
dataset = pd.read_csv(
        'contoh_dataset.csv',
        delimiter=';',
        header='infer',
        index_col=False
        )

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
dataset.head()

Province   Age       Wage Life Insured
0       Banten  24.0  5000000.0          Yes
1  DKI Jakarta   NaN  3400000.0           No
2   Jawa Barat  60.0  7350000.0           No
3       Banten  34.0  3500000.0           No
4   Jawa Barat  58.0        NaN          Yes

#**Menangani Nilai Kosong (NaN)**

---

In [ ]:
# menangani nilai kosong
from sklearn.impute import SimpleImputer

# ganti NaN dengan mean kolom itu
imputer = SimpleImputer(
        missing_values=np.nan,
        strategy='mean'
        )
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.40000000e+01,
        5.00000000e+06],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.60000000e+01,
        3.40000000e+06],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 6.00000000e+01,
        7.35000000e+06],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.40000000e+01,
        3.50000000e+06],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 5.80000000e+01,
        6.27916667e+06],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.60000000e+01,
        8.00000000e+06],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.10000000e+01,
        5.50000000e+06],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        1.00000000e+07],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.00000000e+01,
        9.00000000e+06],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.10000000e+01,
        1.05000000e+07],
       [1.00000000e+00, 0.0000

#**Mengkodekan Daa Kategori**

---


In [ ]:
# kodekan data kategori
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# kodekan nama provinsi (kolom ke-0)
# kode hanya sebatas penanda
encoder_X = ColumnTransformer(
        [('province_encoder', OneHotEncoder(), [0])],
        remainder='passthrough'
        )
X = encoder_X.fit_transform(X).astype(float) # mengembalikan ke dalam tipe 'float64'

In [ ]:
print(encoder_X.named_transformers_['province_encoder'].categories_)

[array(['Banten', 'DKI Jakarta', 'Jawa Barat'], dtype=object)]


In [ ]:
# y adalah dependent, cukup kodekan ke angka
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [ ]:
y

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1])

#**Membagi dataset ke dalam training set dan test set**

---



In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
# kemudian:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)

In [ ]:
X_train

array([[ 1.        , -1.        , -1.        , -0.66666667, -0.36666667],
       [ 1.        , -1.        , -1.        , -0.55555556, -0.40694444],
       [-1.        ,  1.        , -1.        , -0.94444444, -1.        ],
       [-1.        , -1.        ,  1.        ,  1.        , -0.05      ],
       [-1.        ,  1.        , -1.        ,  0.5       ,  1.        ],
       [-1.        ,  1.        , -1.        , -0.33333333,  0.16666667],
       [-1.        , -1.        ,  1.        , -0.66666667, -0.40694444],
       [-1.        , -1.        ,  1.        , -0.11111111,  0.5       ],
       [ 1.        , -1.        , -1.        , -1.        , -0.83333333]])

In [62]:
X_val

array([[0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 5.80000000e+01,
        6.27916667e+06],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.60000000e+01,
        3.40000000e+06],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.90000000e+01,
        2.20000000e+06]])

In [63]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 1, 1])

In [64]:
y_val

array([1, 0, 1])

#**Feature Scaling**
---

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# variabel dummy kode provinsi juga diskalakan
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [65]:
X_train

array([[ 1.        , -1.        , -1.        , -0.66666667, -0.36666667],
       [ 1.        , -1.        , -1.        , -0.55555556, -0.40694444],
       [-1.        ,  1.        , -1.        , -0.94444444, -1.        ],
       [-1.        , -1.        ,  1.        ,  1.        , -0.05      ],
       [-1.        ,  1.        , -1.        ,  0.5       ,  1.        ],
       [-1.        ,  1.        , -1.        , -0.33333333,  0.16666667],
       [-1.        , -1.        ,  1.        , -0.66666667, -0.40694444],
       [-1.        , -1.        ,  1.        , -0.11111111,  0.5       ],
       [ 1.        , -1.        , -1.        , -1.        , -0.83333333]])

In [66]:
X_test

array([[ 1.        , -1.        , -1.        , -0.44444444, -1.33333333],
       [ 1.        , -1.        , -1.        ,  0.11111111,  0.83333333],
       [ 1.        , -1.        , -1.        , -1.16666667, -0.66666667]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range=(-1, 1))
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [67]:
X_train

array([[ 1.        , -1.        , -1.        , -0.66666667, -0.36666667],
       [ 1.        , -1.        , -1.        , -0.55555556, -0.40694444],
       [-1.        ,  1.        , -1.        , -0.94444444, -1.        ],
       [-1.        , -1.        ,  1.        ,  1.        , -0.05      ],
       [-1.        ,  1.        , -1.        ,  0.5       ,  1.        ],
       [-1.        ,  1.        , -1.        , -0.33333333,  0.16666667],
       [-1.        , -1.        ,  1.        , -0.66666667, -0.40694444],
       [-1.        , -1.        ,  1.        , -0.11111111,  0.5       ],
       [ 1.        , -1.        , -1.        , -1.        , -0.83333333]])

In [68]:
X_test

array([[ 1.        , -1.        , -1.        , -0.44444444, -1.33333333],
       [ 1.        , -1.        , -1.        ,  0.11111111,  0.83333333],
       [ 1.        , -1.        , -1.        , -1.16666667, -0.66666667]])